### ISSUE TITLE
Publish on PyPI

### ISSUE THREAD

**Issue by sneakers-the-rat** [datajoint/element-event#17]
README says `pip install element-trial`

but no package is found on pypi: https://pypi.org/project/element-trial/

plz advise if i should pin the repo or if there's some way i can help w/ packaging.

same as: https://github.com/datajoint/element-deeplabcut/issues/20

**Comment by kabilar** [comment]
Thanks for the report @sneakers-the-rat.  The README is mistaken as `element-trial` should now be `element-event`.  I have submitted pull request #18.

We just went through a development push.  We will be tagging and releasing these changes to pypi by the end of May.  For the interim, please install from source:

```
pip install git+https://github.com/datajoint/element-event.git
```

Install a specific commit:
```
pip install git+https://github.com/datajoint/element-event.git@<Enter commit hash>
```

**Comment by sneakers-the-rat** [comment]
Great, having no problem installing the package, just wondering for the purpose of specifying dependencies in downstream packages -- should I pin the repository or should i pin the PyPI version? if the former, is the main branch stable enough to pin? The problem with depending on a repository is that you either need to pin a specific commit (brittle) or a specific branch (unstable) rather than being able to pin a semver range, so am wondering if in the future the repository will run far ahead of the pypi version? 

not trying to be prickly, and completely understand this is a relatively new project, just wondering about release schedules!

consolidating discussion here for related issues  https://github.com/datajoint/element-deeplabcut/issues/20 https://github.com/datajoint/element-session/issues/18 https://github.com/datajoint/element-array-ephys/issues/67

**Comment by kabilar** [comment]
Thanks @sneakers-the-rat.  `element-event` is now on [PyPI](https://pypi.org/project/element-event/).  Going forward I would suggest to pin to the PyPI version for the reasons you described.  As new features are added to the base repository's `main` branch we will be publishing them to PyPI within that week.
